# Generated by Django 4.1.4 on 2022-12-23 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='advert',
            name='car_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
